server:
  port: 8090

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/YGC_Exam_24_10_FAQ?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  type-aliases-package: com.example.demo.vo
